<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ © 2026 by Intellectual Reserve, Inc. All rights reserved.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.familysearch.intern.onboading</groupId>
    <artifactId>springboard-root</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>springboard-acceptance</artifactId>

  <name>Intern Springboard Project Acceptance Tests</name>

  <dependencies>
    <dependency>
      <groupId>org.familysearch.stack.java</groupId>
      <artifactId>java-stack-starter-test</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.familysearch.stack.java</groupId>
      <artifactId>java-stack-assertj-spring</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>com.jayway.jsonpath</groupId>
      <artifactId>json-path</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

  <build>
    <finalName>${project.artifactId}</finalName>

    <!-- The filtering must be on for the resources to fill in the test property values -->
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>

    <plugins>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <configuration>
          <useDefaultDelimiters>false</useDefaultDelimiters>
          <delimiters>
            <delimiter>${*}</delimiter>
          </delimiters>
          <outputDirectory/>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <groups>!AcceptanceTest</groups>
          <!-- To provide jacoco coverage configuration, we need to add @{argLine} here for its injection. -->
          <argLine>@{argLine}</argLine>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>validation-pipeline-acceptance</id>
      <activation>
        <property>
          <!-- Activate in the validation pipeline -->
          <name>acceptance.testing</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
              <!-- Don't execute unit tests during the validation pipeline. Already executed in the build pipeline. -->
              <skipTests>true</skipTests>
            </configuration>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <groups>AcceptanceTest</groups>
              <includes>
                <include>**/*.java</include>
              </includes>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>