#
# © 2026 by Intellectual Reserve, Inc. All rights reserved.
#

spring.profiles.include=${FS_SYSTEM_NAME:local}

# Elastic Beanstalk configures the nginx proxy to forward requests to the application on port 5000
server.port=5000

# Logging config
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS
logging.pattern.level=%-5p
logging.exception-conversion-word=%ex
# Override the spring boot default console pattern.
logging.pattern.console=%d{${LOG_DATEFORMAT_PATTERN}} %clr(${LOG_LEVEL_PATTERN}) %clr(${PID}){magenta} \\(%t\\) %clr([%logger{0}]){cyan} %mdc %m%n${LOG_EXCEPTION_CONVERSION_WORD}
logging.level.root=info
logging.level.org.familysearch.intern.springboard=info
logging.level.org.springframework=info
logging.level.org.familysearch.stack.java=info

# Export metrics to Splunk (When you are ready to export metrics to splunk, please change to true)
# After enabling and deploying, please ensure your application metric URIs are properly templated.
# See https://familysearch.splunkcloud.com/en-US/app/platform_svc_java_stack/java_stack_metrics_usage_scorecard
management.statsd.metrics.export.enabled=false

service.bindings.standards.name-seg=locate://ws.name-seg.standards.service
service.bindings.tree.name-search=locate://tree-names.homelands.service

# StandardsNameClient retry configuration
client.retry.initial-delay-ms=100
client.retry.max-attempts=3