#
# © 2026 by Intellectual Reserve, Inc. All rights reserved.
#

# Set properties otherwise injected by the platform for local development
fs.platform.blueprint.environment=dev
fs.platform.blueprint.blueprint-name=intern-onboarding-springboard
fs.platform.blueprint.system-name=local
fs.platform.blueprint.service-name=webapp

# Metrics
management.statsd.metrics.export.enabled=false

# Pretty-print JSON responses
spring.jackson.serialization.indent_output=true
